require conf/distro/poky.conf

DISTRO = "poky-hybris"
DISTROOVERRIDES =. "poky:"

POKY_INIT_MANAGER:poky-hybris = "systemd"

POKY_DEFAULT_DISTRO_FEATURES = ""
POKY_DEFAULT_EXTRA_RDEPENDS = "packagegroup-core-boot"
POKY_DEFAULT_EXTRA_RRECOMMENDS = "kernel-module-af-packet"
