require conf/distro/poky.conf

DISTRO = "poky-hybris"
DISTROOVERRIDES =. "poky:"

INIT_MANAGER = "systemd"

DISTRO_FEATURES:append = " \
	lto \
	"

DISTRO_FEATURES:remove = " \
	alsa \
	bluetooth \
	multiarch \
	nfc \
	opengl \
	pci \
	pcmcia \
	ptest \
	pulseaudio \
	seccomp \
	vulkan \
	wayland \
	wifi \
	x11 \
	"

DISTRO_EXTRA_RDEPENDS:append = " \
	packagegroup-core-full-cmdline \
	"

DISTRO_EXTRA_RRECOMMENDS:append = " \
	"

# Replace busybox with coreutils
PREFERRED_PROVIDER_virtual/base-utils = "packagegroup-core-base-utils"
VIRTUAL-RUNTIME_base-utils = "packagegroup-core-base-utils"
VIRTUAL-RUNTIME_base-utils-hwclock = "util-linux-hwclock"
VIRTUAL-RUNTIME_base-utils-syslog = ""
